### ISSUE TITLE
UAC ReadMe Command Error

### ISSUE THREAD

**Issue by Fsjgzjs** [DefinetlyNotAI/Data_Voyager#4]
**Describe the bug**
Readme command for UAC is wrong 

**To Reproduce**
1. Go to the UAC command in the readme.md file

**Expected behavior**
To run UACX.py as admin

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Samsung 
 - OS: android 14
 - Browser: Opera GX
 - Version: Latest

**Priority:** 
Medium

**Comment by DefinetlyNotAI** [comment]
Fixed it!
